spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbspotmusic?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
     
        show_sql: true
        hbm2ddl:
          auto: update